### ISSUE TITLE
Update to newest version of Metropolis

### ISSUE THREAD

**Issue by z-y-huang** [gslab-econ/mtheme#4]
Current fork is based off of an older version of Metropolis that is no longer compatible with the latest version of TeX.

**Comment by z-y-huang** [comment]
@gentzkow:

Some follow-ups from your email from last week:

* I have created a branch that updates the Metropolis version to 2017. From some preliminary testing, I believe it is compatible with TeX 2015 and beamers created with Metropolis 2015. 
* There is a way to have the .sty files nested in a subfolder (involves switching the `use*theme(name)` commands to `\usepackage{subfolder/beamerthemename}`. However, we do need to set the name of the subfolder in the .sty files. Currently, I am using `themes`.

**Comment by gentzkow** [comment]
Thanks @z-y-huang. I just tested this in /SocialMediaEffects/ and it compiled fine for me. Good work!

Can you say a little more about why the subfolder needs to be set in the .sty files? That seems unfortunate.

In any case, to wrap this up it would be great if you could:
1. Switch /gentzkow/template/ to use the updated version and format w/ the subfolder
2. Notify the rest of the gslab team so they can update the gslab template / instructions as well
3. Make sure we've killed any references in documentation to directly installing the gslab_metropolis theme (since from now on we'll always store it locally)

**Comment by gentzkow** [comment]
Oh, and if there's no way around the hard-coded subfolder name, let's make the name `beamer_themes`.

**Comment by z-y-huang** [comment]
@gentzkow:

When your beamer document loads `beamerthememetropolis_gslab`,  `beamerthememetropolis_gslab` additionally loads the other theme files (see lines 82 to 90 [here](https://github.com/gslab-econ/mtheme/blob/90306b0ac53ed49a43af25e32914d02915410f62/beamerthememetropolis_gslab.sty)).

It's loading these with the root being the directory of the beamer, so the subfolder containing all of the theme files needs to be specified.

We can load the other theme files individually (since that's really all `beamerthememetropolis_gslab` is doing), though that would mean users would have to copy a lot of (potentially confusing) code into their beamers instead of a single line.

I tried looking to see if there was a way to have the root being the directory of `beamerthememetropolis_gslab`, but haven't had luck so far.

**Comment by gentzkow** [comment]
Got it. Thanks.

I think the approach of loading the other theme files individually is
better, even though it's a bit clunky. At least that way it's explicit to
the user what's going on.

**Comment by z-y-huang** [comment]
@gentzkow:

I have changed the code so that users now have to load the individual theme files, but can set the name of the subfolder however they choose. I have also updated the [README](https://github.com/gslab-econ/mtheme/blob/f7836036d26c27f3877df4b0bb65c5def58d4b5a/README.md) to reflect our new procedure.

Should I merge this branch to `master` and archive the old version in a branch?

**Comment by gentzkow** [comment]
Yes, perfect.

And then you can give the rest of the GSLab team an update.

thanks!

>
